from sqlalchemy import Column, Integer, String, Text, DateTime
from sqlalchemy.sql import func
from database import Base

class Requirement(Base):
    __tablename__ = "requirements"

    id = Column(Integer, primary_key=True, index=True)
    target_field_name = Column(String(255), nullable=True)
    description = Column(Text, nullable=True)
    target_datamart = Column(String(255), nullable=True)
    target_field_type = Column(String(255), nullable=True)
    primary_key = Column(String(255), nullable=True)
    business_key = Column(String(255), nullable=True)
    nullable = Column(String(255), nullable=True)
    default_value = Column(String(255), nullable=True)
    source_field = Column(String(255), nullable=True)
    source_object_event = Column(String(255), nullable=True)
    source_system_topic = Column(String(255), nullable=True)
    source_type = Column(String(255), nullable=True)
    transformation_rules = Column(Text, nullable=True)
    is_derived_value = Column(String(255), nullable=True)
    derived_value_logic = Column(Text, nullable=True)
    data_quality_rules = Column(Text, nullable=True)
    foreign_key_reference_table = Column(String(255), nullable=True)
    foreign_key_reference_field = Column(String(255), nullable=True)
    pii_flag = Column(String(255), nullable=True)
    sensitivity_level = Column(String(255), nullable=True)
    security_rule = Column(String(255), nullable=True)
    retention_policy = Column(String(255), nullable=True)
    archiving_policy = Column(String(255), nullable=True)
    source_retention = Column(String(255), nullable=True)
    source_archiving_policy = Column(String(255), nullable=True)
    data_owner = Column(String(255), nullable=True)
    data_steward = Column(String(255), nullable=True)
    comment_notes = Column(Text, nullable=True)
    storage = Column(String(255), nullable=True)
    latency_requirements = Column(String(255), nullable=True)
    is_renamed = Column(String(255), nullable=True)
    sla_datamart_level = Column(String(255), nullable=True)
    archiving_datamart_level = Column(String(255), nullable=True)
    retention_datamart_level = Column(String(255), nullable=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
